### ISSUE TITLE
How it's work?

### ISSUE THREAD

**Issue by meugr** [nsicko42/jjy-emulator-using-raspberry-pi#2]
Please tell how it works?
Does it only work with the Japanese time zone? Is it possible to synchronize in other time zones? Do I need to connect headphones to raspberry, or do I need to connect an antenna to an 18 pin GPIO? Please explain in more detail what and how to do.
Thank you

**Comment by nsicko42** [comment]
> Does it only work with the Japanese time zone?

No.

> Is it possible to synchronize in other time zones?

Of course. It uses just only the Raspberry Pi system time.

> Do I need to connect headphones to raspberry, or do I need to connect an antenna to an 18 pin GPIO?

You don't need to connect headphones.
You just need to connect the 40kHz or 60kHz loop antenna to GPIO18(Header pin no.12, WiringPi 1) and GND.
